### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by ZloyGolub** [ZloyGolub/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by AndriiKolosov** [comment]
### **Résumé**
— Hello! I’m Kolosov Andrii, a starting front end web developer. I'm starting frontend developer with react, react-redux, redux basic skills, a responsible and attention to detail person. I also have little experience in creating small databases and basic skills with ASP. Core MVC.

**Comment by ZloyGolub** [comment]
### **Résumé**
```
<h2>Résumé</h2>
  <p>&mdash; Hello! I’m Kolosov Andrii, a starting front end web developer.
	I'm starting frontend developer with react, react-redux, redux basic skills, a responsible and attention to detail person. 
	I also have little experience in creating small databases and basic skills with ASP. Core MVC.
  </p>
```
