### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ZloyGolub** [ZloyGolub/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by bdnfdn** [comment]
LIFE & EDUCATION
To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.

LANGUAGES
�� ENGLISH �� MANDARIN �� JAPANESE

SKILLS
KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS

CHARACTER
NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE

LIFE LESSON
You must defeat Sheng Long to stand a chance.

LIKES �
GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY

DISLIKES �
BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES

WANTS �
BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY

**Comment by bdnfdn** [comment]
ACHIEVEMENTS
* #1 in "Top 25 Street Fighter Characters" by IGN, who also called me "fancy", "icon" and "a testament to the virtue of simplicity" ❤️
* #2 in "Top 20 Street Fighter Characters of All Time" by GameDaily, same council found me worth of #6 place in "Top 25 Capcom Characters of All Time", which I proudly share with my partner Ken
* I was named "5th Most Powerful Street Fighter Character" by Screen Rant-san
* #71 in "Top 100 Heroes of All Time" by UGO Networks, also recognized #2 in their list of "Top 50 Street Fighter Characters"
* In a survey of 4000 online matches for Super Street Fighter IV, I got to be the most popular character, with 16.6% of players choosing my side

**Comment by ZloyGolub** [comment]
**Languages**
<section>
  <h3>Languages</h3>
  <p class="tags small">
	<strong>
	  🇷🇺 
	  <span>Russian</span>
	  🇺🇸 
	  <span>English</span>
	  🇺🇦 
	  <span>Ukrainian</span>
	</strong>
  </p>
</section>

**Skills**
<section>
  <h3>Skills</h3>
  <p class="tags small">
	C C++ C# CSS HTML JS REACT REDUX MySQL 
	<span class="nowrap">T-SQL</span> 
	PHOTOSHOP 
	<span class="nowrap">SONY VEGAS</span>
	<span class="nowrap">3D MAX</span>
	WINDOWS NPM                
  </p>
</section>

**Character**
<section>
  <h3>Character</h3>
  <p class="tags small">
	SENSITIVE VULNERABLE 
	<span class="nowrap">COLD-BLOODED</span> 
	RELIABLE CRUEL SILENT SURE
  </p>
</section>

**Likes**
<section>
  <h3>Likes</h3>
  <p class="tags small">
	BICYCLES MOVIES MOTORCYCLES CATS 
	<span class="nowrap">FRESH AIR</span> 
	WALKS NATURE SHOOTERS
  </p>
</section>

**Dislikes**
<section>
  <h3>Dislikes</h3>
  <p class="tags small">
	<span>LOUD SOUNDS</span>
	<span>DOING USELESS THINGS</span> 
	IDIOTS PIKACHU SMOKING🚭
  </p>
</section>

**Wants**
<section>
  <h3>Wants</h3>
  <p class="tags small bulleted">
	<span class="tag">WANT TO BE HAPPY </span>
	<span class="tag">TO BE YOURSELF </span>
	<span class="tag">TO HAVE MORE FREE TIME </span>
  </p>
</section>

**Education**
<section>
  <h3>Education</h3>
  <p class="tags small ">
	<div>
	  <em>1<sup>st</sup> September 2014 &ndash; 31 <sup>th</sup> June 2018</em>
	</div>
	<div>
	  <strong>College of Engineering and Management NAU</strong>
	</div>
	<div>
	  <em>1<sup>st</sup> September 2018 &ndash; to now</em>
	</div>
	<div>
	  <strong>National Aviation University</strong>
	</div>
  </p>
</section>

**Articles**
<section>
  <h3>Articles</h3>
  <p class="tags small">
	Don't have any articles 
  </p>
</section>
