### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by ZloyGolub** [ZloyGolub/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by AndriiKolosov** [comment]
### **Languages**
**🇷🇺 Russian 🇺🇸 English 🇺🇦 Ukrainian**

### **Skills**
C C++ C# CSS HTML JS REACT REDUX MySQL T-SQL PHOTOSHOP SONY VEGAS 3D MAX WINDOWS NPM

### **Character**
SENSITIVE VULNERABLE COLD-BLOODED RELIABLE CRUEL SILENT SURE

### **Likes**
BICYCLES MOVIES MOTORCYCLES CATS FRESH AIR WALKS NATURE SHOOTERS

### **Dislikes**
LOUD SOUNDS DOING USELESS THINGS IDIOTS PIKACHU SMOKING🚭

### **Wants**
WANT TO BE HAPPY TO BE YOURSELF TO HAVE MORE FREE TIME

### **Education**
_1st September 2014 – 31 th June 2018_
**College of Engineering and Management NAU**
_1st September 2018 – to now_
**National Aviation University**

### **Articles**
Don't have any articles

**Comment by ZloyGolub** [comment]
**Languages**
```
<section>
  <h3>Languages</h3>
  <p class="tags small">
	<strong>
	  🇷🇺 
	  <span>Russian</span>
	  🇺🇸 
	  <span>English</span>
	  🇺🇦 
	  <span>Ukrainian</span>
	</strong>
  </p>
</section>
```
**Skills**
```
<section>
  <h3>Skills</h3>
  <p class="tags small">
	C C++ C# CSS HTML JS REACT REDUX MySQL 
	<span class="nowrap">T-SQL</span> 
	PHOTOSHOP 
	<span class="nowrap">SONY VEGAS</span>
	<span class="nowrap">3D MAX</span>
	WINDOWS NPM                
  </p>
</section>
```
**Character**
```
<section>
  <h3>Character</h3>
  <p class="tags small">
	SENSITIVE VULNERABLE 
	<span class="nowrap">COLD-BLOODED</span> 
	RELIABLE CRUEL SILENT SURE
  </p>
</section>
```
**Likes**
```
<section>
  <h3>Likes</h3>
  <p class="tags small">
	BICYCLES MOVIES MOTORCYCLES CATS 
	<span class="nowrap">FRESH AIR</span> 
	WALKS NATURE SHOOTERS
  </p>
</section>
```
**Dislikes**
```
<section>
  <h3>Dislikes</h3>
  <p class="tags small">
	<span>LOUD SOUNDS</span>
	<span>DOING USELESS THINGS</span> 
	IDIOTS PIKACHU SMOKING🚭
  </p>
</section>
```
**Wants**
```
<section>
  <h3>Wants</h3>
  <p class="tags small bulleted">
	<span class="tag">WANT TO BE HAPPY </span>
	<span class="tag">TO BE YOURSELF </span>
	<span class="tag">TO HAVE MORE FREE TIME </span>
  </p>
</section>
```
**Education**
```
<section>
  <h3>Education</h3>
  <p class="tags small ">
	<div>
	  <em>1<sup>st</sup> September 2014 &ndash; 31 <sup>th</sup> June 2018</em>
	</div>
	<div>
	  <strong>College of Engineering and Management NAU</strong>
	</div>
	<div>
	  <em>1<sup>st</sup> September 2018 &ndash; to now</em>
	</div>
	<div>
	  <strong>National Aviation University</strong>
	</div>
  </p>
</section>
```
**Articles**
```
<section>
  <h3>Articles</h3>
  <p class="tags small">
	Don't have any articles 
  </p>
</section>
```
